name: shopack_user
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  carousel_slider: ^4.2.0
  cloudinary_sdk: ^4.0.2+10
  build_runner: ^2.3.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter_dotenv: ^5.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_rating_bar: ^4.0.1
  flutter_typeahead: ^4.1.1
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get_it: ^7.2.0
  google_maps_flutter: ^2.2.2
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  image_picker: ^0.8.6
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  lottie: ^2.1.0
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  shared_preferences: ^2.0.15
  uuid: ^3.0.7
  fl_country_code_picker: ^0.0.4
dev_dependencies:
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
